--- #YAML:1.0
name:               Email-Abstract
version:            3.000
abstract:           ~
author:  []
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
requires:
    Class::ISA:         0.20
    Email::Simple:      1.91
    Module::Pluggable:  1.5
    Test::More:         0.47
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.48
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
