# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Email-Abstract
version:      2.0
version_from: lib/Email/Abstract.pm
installdirs:  site
requires:
    Email::Simple:                 0
    Module::Pluggable:             0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.21
