# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Email-Abstract
version:      2.10
version_from: lib/Email/Abstract.pm
installdirs:  site
requires:
    Class::ISA:                    0.20
    Email::Simple:                 1.91
    Module::Pluggable:             1.5
    Test::More:                    0.47

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
