#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Email-Abstract
version:      1.0
version_from: lib/Email/Abstract.pm
installdirs:  site
requires:
    Module::Pluggable:             0
    Email::Simple:                 0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.12
