--- #YAML:1.0
name:                Email-Abstract
version:             2.133_04
abstract:            ~
license:             perl
generated_by:        ExtUtils::MakeMaker version 6.32
distribution_type:   module
requires:     
    Class::ISA:                    0.20
    Email::Simple:                 1.91
    Module::Pluggable:             1.5
    Test::More:                    0.47
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
